### ISSUE TITLE
Image on the docker hub seems to be corrupted

### ISSUE THREAD

**Issue by numo68** [joelnb/dockerfiles#1]
Something happened to the image on the docker hub

docker-compose.yml:

```
services:
  personalweb:
    image: joelnb/nginx-digest
    ...
```

```
# docker-compose pull
Pulling personalweb ...

ERROR: for personalweb  error pulling image configuration: unknown blob
ERROR: error pulling image configuration: unknown blob
```

Thanks

**Comment by joelnb** [comment]
Sorry about this but I've no idea what caused it - there was nothing obvious on the Docker Hub side but I was getting the same issue. I forced a rebuild and it seems to be working okay now.

**Comment by numo68** [comment]
works now, many thanks!
